project:
  type: website

website:
  title: "Introduction to DS/ML"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: home
      - href: about.qmd
        text: 'Acerca de'
      - href: \docs\context_and_concepts\context_and_concepts.qmd
        text: Course presentation
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/vicmanr90/
        text: LinkedIn de Víctor Mario Noble Ramos
  sidebar:
    - id: intro
      collapse-level: 1
      style: floating
      contents: 
        - docs/intro/intro.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



