project:
  type: website

website:
  title: "Introduction to machine learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: 'Acerca de'
      - href: slides.qmd
        text: Tema 1
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/vicmanr90/
        text: LinkedIn de Víctor Mario Noble Ramos

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



